import pkg from 'pg';
const { Client } = pkg;
import dotenv from 'dotenv';
dotenv.config();

const dbUrl = process.env.DATABASE_URL;

if (!dbUrl) {
  console.error('DATABASE_URL is missing in .env');
  process.exit(1);
}

const client = new Client({
  connectionString: dbUrl,
  ssl: { rejectUnauthorized: false }
});

async function setupDatabase() {
  console.log('Connecting to Supabase PostgreSQL database...');
  await client.connect();

  console.log('Creating "sessions" and "clicks" tables...');

  await client.query(`
    CREATE TABLE IF NOT EXISTS sessions (
      session_id TEXT PRIMARY KEY,
      ip TEXT,
      city TEXT,
      state TEXT,
      country TEXT,
      country_code TEXT,
      org TEXT,
      isp TEXT,
      device_type TEXT,
      os TEXT,
      browser TEXT,
      screen_res TEXT,
      referrer TEXT,
      entry_page TEXT,
      start_time TIMESTAMPTZ DEFAULT NOW(),
      last_ping TIMESTAMPTZ DEFAULT NOW(),
      duration_seconds INT DEFAULT 0
    );
  `);

  await client.query(`
    CREATE TABLE IF NOT EXISTS clicks (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      session_id TEXT REFERENCES sessions(session_id) ON DELETE CASCADE,
      link_url TEXT,
      link_text TEXT,
      link_type TEXT,
      section TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );
  `);

  await client.query(`
    ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
    ALTER TABLE clicks ENABLE ROW LEVEL SECURITY;
  `);

  await client.query(`
    DO $$ 
    BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public session inserts') THEN
        CREATE POLICY "Allow public session inserts" ON sessions FOR INSERT WITH CHECK (true);
      END IF;
      IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public session updates') THEN
        CREATE POLICY "Allow public session updates" ON sessions FOR UPDATE USING (true);
      END IF;
      IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public session select') THEN
        CREATE POLICY "Allow public session select" ON sessions FOR SELECT USING (true);
      END IF;
      IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public click inserts') THEN
        CREATE POLICY "Allow public click inserts" ON clicks FOR INSERT WITH CHECK (true);
      END IF;
      IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public click select') THEN
        CREATE POLICY "Allow public click select" ON clicks FOR SELECT USING (true);
      END IF;
    END $$;
  `);

  console.log('✅ Supabase database schema initialized successfully!');
  await client.end();
}

setupDatabase().catch(err => {
  console.error('Failed to initialize Supabase schema:', err.message);
  process.exit(1);
});
