-- Supabase Schema for Ashwin's Portfolio Analytics
-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

CREATE TABLE IF NOT EXISTS sessions (
  session_id TEXT PRIMARY KEY,
  ip TEXT,
  city TEXT,
  state TEXT,
  country TEXT,
  country_code TEXT,
  org TEXT,
  isp TEXT,
  device_type TEXT,
  os TEXT,
  browser TEXT,
  screen_res TEXT,
  referrer TEXT,
  entry_page TEXT,
  start_time TIMESTAMPTZ DEFAULT NOW(),
  last_ping TIMESTAMPTZ DEFAULT NOW(),
  duration_seconds INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS clicks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT REFERENCES sessions(session_id) ON DELETE CASCADE,
  link_url TEXT,
  link_text TEXT,
  link_type TEXT,
  section TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) and allow anon inserts/reads for analytics
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE clicks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public session inserts" ON sessions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public session updates" ON sessions FOR UPDATE USING (true);
CREATE POLICY "Allow public session select" ON sessions FOR SELECT USING (true);

CREATE POLICY "Allow public click inserts" ON clicks FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public click select" ON clicks FOR SELECT USING (true);
